### ISSUE TITLE
Fixing build on BSDs

### ISSUE THREAD

**Issue by mmcco** [kohler/masstree-beta#22]
For what it's worth, one needs to add `-lexecinfo` to `$LIB` to build on OpenBSD and FreeBSD (and, I would assume, NetBSD). This is because `backtrace(3)` and friends are stored there rather than in libc. I tried to find an elegant way to add this to `configure.ac`, but I have little experience with autoconf and it seems that masstree doesn't yet use the features necessary for `AC_CANONICAL_TARGET` or `AC_CANONICAL_HOST`.

If there's an easy way of adding it, it'd be appreciated. Otherwise, it's easy to manually patch into `GNUMakefile.in`.

**Comment by kohler** [comment]
The Autoconf way is not to check for specific targets, but to check for individual features. This should work!
