### ISSUE TITLE
In-consistency bug

### ISSUE THREAD

**Issue by idanlevy1234** [kohler/masstree-beta#40]
This issue is about a key that was inserted successfully to the tree but failed to be retrieved or deleted. Inserting the same key again might succeed.

**Scenario:**
     Thread 1: Inserting key A. Traversing down the tree looking for the right leaf
     Thread 2: Deleting key B, where B > A and keys share partial\full internode route to the leafs.
     Thread 2: Deleting key B, which is the last key in leaf X (Leaf X is now empty). 
     Thread 2: Deleting leaf X and redirect new key boundary.
     Thread 1: Finish insert key A successfully but the key is not reachable.

**Comment by kohler** [comment]
Hi Idan,

I’m trying to make some progress on this issue and getting blocked.

**Into which leaf node is key A inserted?** Is it inserted into leaf X? If not, then where?

I would expect for Thread 1’s insertion to hit a null pointer in the internal node, after which Thread 1 would try to insert again from the root.

Would love to see the benchmark you used to find this.

**Comment by kohler** [comment]
I think I figured it out and have a solution that wastes some memory but is otherwise ok.

Analysis of problem:

![image](https://user-images.githubusercontent.com/410647/67643165-b12c0a80-f8ea-11e9-8062-3b68c8ad0f02.png)

**Comment by kohler** [comment]
Going to leave open until we confirm this solution.

**Comment by idanlevy1234** [comment]
Fix was validated
